/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentDrawRouteImport } from './routes/tournament-draw'
import { Route as TopScorersRouteImport } from './routes/top-scorers'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as SquadsRouteImport } from './routes/squads'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as HallOfMemoryRouteImport } from './routes/hall-of-memory'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesIndexRouteImport } from './routes/matches.index'
import { Route as SeasonYearRouteImport } from './routes/season.$year'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as MatchesMatchIdRouteImport } from './routes/matches.$matchId'
import { Route as ClubsSlugRouteImport } from './routes/clubs.$slug'

const TournamentDrawRoute = TournamentDrawRouteImport.update({
  id: '/tournament-draw',
  path: '/tournament-draw',
  getParentRoute: () => rootRouteImport,
} as any)
const TopScorersRoute = TopScorersRouteImport.update({
  id: '/top-scorers',
  path: '/top-scorers',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadsRoute = SquadsRouteImport.update({
  id: '/squads',
  path: '/squads',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfMemoryRoute = HallOfMemoryRouteImport.update({
  id: '/hall-of-memory',
  path: '/hall-of-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MatchesRoute,
} as any)
const SeasonYearRoute = SeasonYearRouteImport.update({
  id: '/season/$year',
  path: '/season/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => MatchesRoute,
} as any)
const ClubsSlugRoute = ClubsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ClubsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/hall-of-memory': typeof HallOfMemoryRoute
  '/matches': typeof MatchesRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/players': typeof PlayersRoute
  '/sponsors': typeof SponsorsRoute
  '/squads': typeof SquadsRoute
  '/standings': typeof StandingsRoute
  '/top-scorers': typeof TopScorersRoute
  '/tournament-draw': typeof TournamentDrawRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/season/$year': typeof SeasonYearRoute
  '/matches/': typeof MatchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/hall-of-memory': typeof HallOfMemoryRoute
  '/news': typeof NewsRouteWithChildren
  '/players': typeof PlayersRoute
  '/sponsors': typeof SponsorsRoute
  '/squads': typeof SquadsRoute
  '/standings': typeof StandingsRoute
  '/top-scorers': typeof TopScorersRoute
  '/tournament-draw': typeof TournamentDrawRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/season/$year': typeof SeasonYearRoute
  '/matches': typeof MatchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/hall-of-memory': typeof HallOfMemoryRoute
  '/matches': typeof MatchesRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/players': typeof PlayersRoute
  '/sponsors': typeof SponsorsRoute
  '/squads': typeof SquadsRoute
  '/standings': typeof StandingsRoute
  '/top-scorers': typeof TopScorersRoute
  '/tournament-draw': typeof TournamentDrawRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/season/$year': typeof SeasonYearRoute
  '/matches/': typeof MatchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/clubs'
    | '/hall-of-memory'
    | '/matches'
    | '/news'
    | '/players'
    | '/sponsors'
    | '/squads'
    | '/standings'
    | '/top-scorers'
    | '/tournament-draw'
    | '/clubs/$slug'
    | '/matches/$matchId'
    | '/news/$slug'
    | '/season/$year'
    | '/matches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/clubs'
    | '/hall-of-memory'
    | '/news'
    | '/players'
    | '/sponsors'
    | '/squads'
    | '/standings'
    | '/top-scorers'
    | '/tournament-draw'
    | '/clubs/$slug'
    | '/matches/$matchId'
    | '/news/$slug'
    | '/season/$year'
    | '/matches'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/clubs'
    | '/hall-of-memory'
    | '/matches'
    | '/news'
    | '/players'
    | '/sponsors'
    | '/squads'
    | '/standings'
    | '/top-scorers'
    | '/tournament-draw'
    | '/clubs/$slug'
    | '/matches/$matchId'
    | '/news/$slug'
    | '/season/$year'
    | '/matches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ClubsRoute: typeof ClubsRouteWithChildren
  HallOfMemoryRoute: typeof HallOfMemoryRoute
  MatchesRoute: typeof MatchesRouteWithChildren
  NewsRoute: typeof NewsRouteWithChildren
  PlayersRoute: typeof PlayersRoute
  SponsorsRoute: typeof SponsorsRoute
  SquadsRoute: typeof SquadsRoute
  StandingsRoute: typeof StandingsRoute
  TopScorersRoute: typeof TopScorersRoute
  TournamentDrawRoute: typeof TournamentDrawRoute
  SeasonYearRoute: typeof SeasonYearRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournament-draw': {
      id: '/tournament-draw'
      path: '/tournament-draw'
      fullPath: '/tournament-draw'
      preLoaderRoute: typeof TournamentDrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-scorers': {
      id: '/top-scorers'
      path: '/top-scorers'
      fullPath: '/top-scorers'
      preLoaderRoute: typeof TopScorersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squads': {
      id: '/squads'
      path: '/squads'
      fullPath: '/squads'
      preLoaderRoute: typeof SquadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-memory': {
      id: '/hall-of-memory'
      path: '/hall-of-memory'
      fullPath: '/hall-of-memory'
      preLoaderRoute: typeof HallOfMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof MatchesRoute
    }
    '/season/$year': {
      id: '/season/$year'
      path: '/season/$year'
      fullPath: '/season/$year'
      preLoaderRoute: typeof SeasonYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof MatchesRoute
    }
    '/clubs/$slug': {
      id: '/clubs/$slug'
      path: '/$slug'
      fullPath: '/clubs/$slug'
      preLoaderRoute: typeof ClubsSlugRouteImport
      parentRoute: typeof ClubsRoute
    }
  }
}

interface ClubsRouteChildren {
  ClubsSlugRoute: typeof ClubsSlugRoute
}

const ClubsRouteChildren: ClubsRouteChildren = {
  ClubsSlugRoute: ClubsSlugRoute,
}

const ClubsRouteWithChildren = ClubsRoute._addFileChildren(ClubsRouteChildren)

interface MatchesRouteChildren {
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
}

const MatchesRouteChildren: MatchesRouteChildren = {
  MatchesMatchIdRoute: MatchesMatchIdRoute,
  MatchesIndexRoute: MatchesIndexRoute,
}

const MatchesRouteWithChildren =
  MatchesRoute._addFileChildren(MatchesRouteChildren)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ClubsRoute: ClubsRouteWithChildren,
  HallOfMemoryRoute: HallOfMemoryRoute,
  MatchesRoute: MatchesRouteWithChildren,
  NewsRoute: NewsRouteWithChildren,
  PlayersRoute: PlayersRoute,
  SponsorsRoute: SponsorsRoute,
  SquadsRoute: SquadsRoute,
  StandingsRoute: StandingsRoute,
  TopScorersRoute: TopScorersRoute,
  TournamentDrawRoute: TournamentDrawRoute,
  SeasonYearRoute: SeasonYearRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
